version: '3.8'

services:
  web:
    image: backend_image
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=rashid
      - POSTGRES_PASSWORD=rashid
      - POSTGRES_DB=image_processing

volumes:
  postgres_data:
